name: ci

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: "18.12.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check formatting
        run: npm run lint-check

      - name: Check for type errors
        run: npm run type-check

      - name: Check for build errors
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

      - name: Run end-to-end tests
        id: e2eTests
        run: npm run test:e2e

      # Uploads the failure screenshots produced by Cypress
      - uses: actions/upload-artifact@v3
        if: always() && (steps.e2eTests.outcome == 'failure')
        name: Upload Cypress failure screenshots
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*.png
          if-no-files-found: ignore
          retention-days: 1
