name: Build Vue
on:
  push:
    branches:
      - stable
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "hackgvl"
          reponame: "open-map-data-multi-layers-demo"
          token: ${{ secrets.GITHUB_TOKEN }}
