name: Deploy to Github pages

on:
  push:
    branches:
      - develop

jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Vue site
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: "hackgvl"
          reponame: "open-map-data-multi-layers-demo"
          token: ${{ secrets.GITHUB_TOKEN }}
